CREATE TABLE users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid VARCHAR(30) UNIQUE NOT NULL,
    nick_name VARCHAR(8) NOT NULL,
    pwd VARCHAR(255) NOT NULL 
);

CREATE TABLE pets(
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE foods(
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE user_pet_catalog(
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     user_id INT UNSIGNED NOT NULL ,
     pet_id INT UNSIGNED NOT NULL ,
     FOREIGN KEY (user_id) REFERENCES users (id),
     FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE TABLE user_current_pet(
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     user_id INT UNSIGNED NOT NULL UNIQUE, 
     pet_id INT UNSIGNED NOT NULL,
     phase INT NOT NULL,
     hungry INT NOT NULL, 
     bored  INT NOT NULL,
     next_level TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     FOREIGN KEY (user_id) REFERENCES users (id),
     FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE TABLE user_foods(
     id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     user_id INT UNSIGNED NOT NULL UNIQUE, 
     food_id INT UNSIGNED NOT NULL,
     food_count INT,
     FOREIGN KEY (user_id) REFERENCES users (id),
     FOREIGN KEY (food_id) REFERENCES foods (id)
);